### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by masa213f**
- Add GitHub Actions workflows
  - `build` ... Execute unit test and e2e test.
  - `release` ... Build a container image and upload asset to GitHub Release.
- Refactor Makefile
  - Add some make targets.
  - Separate a makefile for csi-sidecars.
  - Get version variable value when building.

### CODE REVIEW

**Comment by zoetrope** [comment]
When would you delete .circleci/config.yaml?
I worry about the release conflicting.

**Comment by ysksuzuki** [comment]
Looks good to me other than ikezoe-san's comments above.

**Comment by tapih** [comment]
> When would you delete .circleci/config.yaml?
> I worry about the release conflicting.

I can remove circleci config in this PR, but the change will be huge.
So, after this PR is merged, I am going to make new PR just for removing the circleci config.

**Comment by tapih** [comment]
> Currently we are deciding whether or not to run a test depending on `CIRCLECI` environment variables.
> 
> https://github.com/cybozu-go/topolvm/blob/9d5902a2d133b6775bde8db3ed1130c178a31f39/lvmd/lvservice_test.go#L20
> 
> 
> https://github.com/cybozu-go/topolvm/blob/c0c629cf4faf854bdceeef6371854c2b8346b0ba/filesystem/interface_test.go#L46
> 
> Do you need to change this for GitHub Actions?

All the workflows run on a virtual machine, so I think the current code runs tests as we intended.
`circleci := os.Getenv("CIRCLECI") == "true" ` will be deleted at the same time I purge the circleci config.

**Pull request merged**
